apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-service-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: frontend-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: frontend-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: frontend-react
          image: registry.gitlab.com/svtslv/public/dev-frontend-react
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: nestjs-kubernetes-secret
